language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
env:
  global:
    - secure: "IDCejLeSEtw2QJsZwLxYXYdqXamd/DvrqEZJ6zVwpV6XD4p1HiJXrGLpd2h99sqVJ+hwYQ7FCvZwULavqQH81QtMRSHk6xb+Imnyk02gWwBRQOoKZeaELE3D8+y4YPQfvcpYBq+TgjJVSU34VvGKPAM3oZNXTogJvSSFyf3OcmyMpKgLe2yR23M/8OC+/XKU7tOFVJfuDsKoxumeqtz+OoXLABNSbbI6K2iO/+JHxMmoYt0Xjx/yy74+rOA0E6s2sMszaiJ/QIBGcTSHoydG/Hb+2rBEHB5sIShWhUdZVpk7iUT6CCq2AL5zW+r7/qvyXGE1wLxb2nNwnUa/rnQvWz4V99Jv9QBhbfabI/xp+eNo9uKCH1LRrKJSdD9cO/ZkZQ30I2+deYciT1qduVDDOAcxc7/WMDhOYlGN+HA7B7xSlbTqsA5OVKF+Cppi+OtKdDX6PxNUWNm8VAg+Wef2USrRWnWBau/aVnUUsTPPLInPQeANh8E9bxknxmTh+VLIysQXid+LvDXNC2eTRkk9CaBGnHK96izvScWB2SUTXICZtQdu8BpWIOwHxK0fwTJZEMCuWe2y1onGNse4sCpyE00nQzKB0KsSC9uJOOIiOlATinRgg17Jomn5T7AGVVrKp9WxrwXERcYOHmNZC8CMuAK5+sKR/7vUwJZkG03QxSI="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "wultra/powerauth-restful-integration"
      description: "Build submitted via Travis CI"
    notification_email: roman.strobl@wultra.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan